import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import ts from "typescript";
const encode=code=>`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`;
const compile=async path=>ts.transpileModule(await readFile(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
const routesUrl=encode(await compile('../lib/title-routes.ts'));
const linksUrl=encode((await compile('../lib/episode-links.ts')).replace('"@/lib/title-routes"',JSON.stringify(routesUrl)));
const {episodePath,episodeKey,readEpisodeTarget,normalizeFavoriteEpisode}=await import(linksUrl);
const episode={tmdbId:123,showTitle:'Example Show',seasonNumber:0,episodeNumber:2,episodeName:'Special',posterUrl:'https://image.tmdb.org/t/p/w500/example.jpg',year:2024};
assert.equal(episodeKey(episode),'123-0-2');
assert.equal(episodePath(episode),'/title/tmdb-show-123-example-show?season=0&episode=2#episode-123-0-2');
assert.deepEqual(readEpisodeTarget('?season=0&episode=2'),{seasonNumber:0,episodeNumber:2});
for(const query of ['?season=-1&episode=2','?season=1&episode=0','?season=&episode=2','?season=1&episode=2.5','?season=1001&episode=1'])assert.equal(readEpisodeTarget(query),null);
assert.equal(normalizeFavoriteEpisode({...episode,tmdbId:-2}),null);
assert.equal(normalizeFavoriteEpisode({...episode,posterUrl:'https://evil.test/tracker'}).posterUrl,undefined);
const adminUrl=encode(`export const writes=[]; export const reads=[]; export let friendExists=true; export function setFriend(value){friendExists=value;} export const adminAuth={async verifyIdToken(token){if(token!=='valid')throw Error('invalid');return {uid:'owner',name:'Owner'};}}; export const adminFirestore={doc(path){return {async get(){reads.push(path);return {exists:friendExists,data:()=>({displayName:'Owner',username:'owner'})};},async set(data){writes.push({path,data});},async delete(){writes.push({path,deleted:true});}};},collection(path){return {orderBy(){return this;},limit(count){if(![500,5000].includes(count))throw Error('unbounded');return this;},async get(){reads.push(path);return {docs:[]};},doc(){return {path:path+'/reco1',id:'reco1'};}};},batch(){const pending=[];return {set(ref,data){pending.push({path:ref.path,data});},async commit(){writes.push(...pending);}};}};`);
// Document references retain their path for assertions and batch writes.
const mockText=Buffer.from(adminUrl.split(',')[1],'base64').toString().replace('return {async get()', 'return {path,async get()');
const actualAdminUrl=encode(mockText);
const admin=await import(actualAdminUrl);
const fieldUrl=encode('export const FieldValue={serverTimestamp:()=>123};');
const apiCode=(await compile('../app/api/episode-actions/route.ts')).replace('"@/lib/firebase-admin"',JSON.stringify(actualAdminUrl)).replace('"@/lib/episode-links"',JSON.stringify(linksUrl)).replace('"firebase-admin/firestore"',JSON.stringify(fieldUrl));
const {GET,POST}=await import(encode(apiCode));
const request=(body,token='valid')=>new Request('https://streamfind.test/api/episode-actions',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
assert.equal((await POST(request({action:'favorite',episode},'invalid'))).status,401);
assert.equal(admin.writes.length,0);
assert.equal((await POST(request(null))).status,400);
assert.equal((await POST(request({action:'favorite',episode:{...episode,episodeNumber:0}}))).status,400);
assert.equal((await POST(request({action:'favorite',episode,uid:'another-user'}))).status,200);
assert.equal(admin.writes.at(-1).path,'users/owner/favoriteEpisodes/123-0-2');
assert.equal((await POST(request({action:'remove',episode}))).status,200);
assert.equal(admin.writes.at(-1).deleted,true);
admin.setFriend(false);const before=admin.writes.length;
assert.equal((await POST(request({action:'share',episode,toUid:'stranger',message:'Try this'}))).status,403);
assert.equal(admin.writes.length,before);
admin.setFriend(true);
for(const toUid of ['owner','evil/path',''])assert.equal((await POST(request({action:'share',episode,toUid}))).status,400);
assert.equal((await POST(request({action:'share',episode,toUid:'friend',message:'x'.repeat(241)}))).status,400);
assert.equal((await POST(request({action:'share',episode,toUid:'friend',message:'Try this episode'}))).status,200);
const recommendation=admin.writes.at(-2).data;const notification=admin.writes.at(-1).data;
assert.equal(recommendation.fromUid,'owner');assert.equal(recommendation.toUid,'friend');assert.equal(recommendation.titlePath,episodePath(episode));assert.equal(recommendation.episode.episodeName,'Special');assert.equal(notification.href,episodePath(episode));assert.equal(notification.imageUrl,episode.posterUrl);
const response=await GET(new Request('https://streamfind.test/api/episode-actions?uid=other',{headers:{Authorization:'Bearer valid'}}));assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'private, no-store');assert.equal(admin.reads.at(-1),'users/owner/favoriteEpisodes');
assert.equal((await GET(new Request('https://streamfind.test/api/episode-actions'))).status,401);
console.log('PASS: canonical deep links, specials, input limits, image validation, authenticated private favorites, account isolation, accepted-friend sharing, atomic Inbox/Activity writes and private responses');

assert.equal((await POST(request({action:'watched',episode,uid:'other'}))).status,200);
assert.equal(admin.writes.at(-1).path,'users/owner/episodeProgress/123/episodes/0-2');
assert.equal(admin.writes.at(-1).data.watchedAt,123);
assert.equal((await POST(request({action:'unwatched',episode}))).status,200);
assert.equal(admin.writes.at(-1).deleted,true);
const progressResponse=await GET(new Request('https://streamfind.test/api/episode-actions?id=123&uid=other',{headers:{Authorization:'Bearer valid'}}));
assert.equal(progressResponse.status,200);
assert.ok(admin.reads.includes('users/owner/episodeProgress/123/episodes'));
assert.deepEqual((await progressResponse.json()).watched,[]);
assert.equal((await GET(new Request('https://streamfind.test/api/episode-actions?id=-1',{headers:{Authorization:'Bearer valid'}}))).status,400);
console.log('PASS: watched/unwatched persistence, authenticated series-scoped progress and input validation');
