import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const encode=code=>`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`;
const compile=async path=>ts.transpileModule(await readFile(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
const routes=encode(await compile('../lib/title-routes.ts'));
const links=encode((await compile('../lib/episode-links.ts')).replace('"@/lib/title-routes"',JSON.stringify(routes)));
const progressModule=encode((await compile('../lib/episode-progress.ts')).replace('"@/lib/episode-links"',JSON.stringify(links)));
const {seasonProgress}=await import(progressModule);
const episodes=[{episodeNumber:1,airDate:'2026-01-01'},{episodeNumber:2,airDate:'2026-01-02'},{episodeNumber:3,airDate:'2027-01-01'}];
const watched=(tmdbId,seasonNumber,episodeNumber)=>({tmdbId,seasonNumber,episodeNumber,showTitle:'Example',episodeName:'Episode'});
let progress=seasonProgress(123,1,episodes,[watched(123,1,2),watched(999,1,1),watched(123,2,1)],'2026-10-03');
assert.equal(progress.count,1);assert.equal(progress.next.episodeNumber,1,'Skipping ahead does not erase unwatched gaps');assert.equal(progress.complete,false);
progress=seasonProgress(123,1,episodes,[watched(123,1,1),watched(123,1,2)],'2026-10-03');
assert.equal(progress.count,2);assert.equal(progress.next,null,'Future episodes are not presented as ready to watch');assert.equal(progress.complete,false);
progress=seasonProgress(123,1,episodes,[watched(123,1,1),watched(123,1,2),watched(123,1,3)],'2027-02-01');
assert.equal(progress.complete,true);assert.equal(progress.next,null);
assert.equal(seasonProgress(123,1,[],[],'2026-10-03').complete,false);
assert.equal(seasonProgress(123,0,[{episodeNumber:2,airDate:null}],[],'2026-10-03').next.episodeNumber,2);
console.log('PASS: season/series isolation, unwatched gaps, upcoming episodes, completed and empty seasons, specials and unknown air dates');
